config/routes.rb
Rails.application.routes.draw do
    root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :organizations do
    resources :invoices
    resources :customers
  end

  resources :invoices do
    resources :line_items
  end

  devise_for :users
  resources :users


end

app/models/invoice.rb
class Invoice < ApplicationRecord

  has_many :customers
  has_many :line_items, dependent: :destroy
  accepts_nested_attributes_for :line_items

  belongs_to :organization
  accepts_nested_attributes_for :organization

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :set_organization

  # GET /invoices
  # GET /invoices.json
  def index
    @organization = Organization.find(params[:organization_id])
    @invoices = @organization.invoice
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @line_items = @invoice.line_items
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @customers = @organization.customer
    @line_items = @invoice.line_items.build
  end

  # GET /invoices/1/edit
  def edit
    @customers = @organization.customer
    @line_items = @invoice.line_items
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = @organization.invoice.build(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to organization_invoices_path(@organization), notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to organization_invoices_path(@organization), notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to organization_invoices_path(@organization), notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def set_organization
      @organization = Organization.find(params[:organization_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:customer, :number, :order_number,
                                      :invoice_date, :salesperson, :terms, :due_date,
                                      :line_items_attributes => [:product, :description, :amount, :unit_price])
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for([@organization, @invoice], html: {class:'form-horizontal'}) do |f| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :customer,  class:'control-label col-xs-2' %>
    <div class="col-xs-4">
      <%= text_field_tag 'invoice[customer]', @invoice.customer, list: 'customers', class:'form-control' %>
      <datalist id="customers">
        <%customers.each do |c|%>
           <option value="<%= c.name %>">
        <%end%>
      </datalist>
      </div>
    <%= link_to 'New Customer', new_organization_customer_path %>

  </div>

    <div class="form-group">
      <%= f.label :number, class:'control-label col-xs-2' %>
      <div class="col-xs-4">
        <%= f.text_field :number, class:'form-control' %>
      </div>
    </div>


    <div class="form-group">
      <%= f.label :order_number, class:'control-label col-xs-2' %>
      <div class="col-xs-4">
        <%= f.text_field :order_number, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :invoice_date, class:'control-label col-xs-2' %>
      <div class="col-xs-4">
        <%= f.date_select :invoice_date, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :salesperson, class:'control-label col-xs-2' %>
      <div class="col-xs-4">
        <%= f.text_field :salesperson, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :terms, class:'control-label col-xs-2' %>
      <div class="col-xs-4">
        <%= f.text_field :terms, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :due_date, class:'control-label col-xs-2' %>
      <div class="col-xs-4">
        <%= f.date_select :due_date, class:'form-control' %>
      </div>
    </div>

    <h3>Line Items</h3>
    <table class="table">
      <thead>
      <tr>
        <th>Product</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Unit Price</th>
      </tr>
      </thead>

      <tbody>
        <%= f.fields_for :line_items do |line_items_fields| %>
          <tr>
            <td><%= line_items_fields.text_field :product%></td>
            <td><%= line_items_fields.text_area :description %></td>
            <td><%= line_items_fields.number_field :amount %></td>
            <td><%= line_items_fields.text_field :unit_price %></td>
          </tr>
        <% end %>
      </tbody>
      <%#= link_to "", class:"btn btn-success" do %>
          <!--<span class="glyphicon glyphicon-plus"></span> New LineItem-->
      <%#end%>
    </table>

    <div class="actions">
      <%= f.submit class:"btn btn-success"  %>
    </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice, customers: @customers %>

<%= link_to 'Show', organization_invoice_path(params[:organization_id], @invoice) %> |
<%= link_to 'Back', organization_invoices_path %>

app/views/invoices/index.html.erb
<h1>Invoices</h1>

<table class="table">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Number</th>
      <th>Order number</th>
      <th>Invoice date</th>
      <th>Salesperson</th>
      <th>Terms</th>
      <th>Due date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.customer %></td>
        <td><%= link_to invoice.number, organization_invoice_path(params[:organization_id], invoice) %></td>
        <td><%= invoice.order_number %></td>
        <td><%= invoice.invoice_date %></td>
        <td><%= invoice.salesperson %></td>
        <td><%= invoice.terms %></td>
        <td><%= invoice.due_date %></td>
        <td>
          <%= link_to edit_organization_invoice_path(params[:organization_id], invoice), class:'btn btn-primary btn-sm' do  %>
              <span class="glyphicon glyphicon-pencil"></span>
          <%end%>
        </td>
        <td>
          <%= link_to  organization_invoice_path(params[:organization_id], invoice), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' do %>
              <span class="glyphicon glyphicon-remove"></span>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= link_to new_organization_invoice_path, class:"btn btn-success" do %>
    <span class="glyphicon glyphicon-plus"></span> New Invoice
<%end%>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice, customers: @customers %>

<%= link_to 'Back', organization_invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @invoice.customer %>
</p>

<p>
  <strong>Number:</strong>
  <%= @invoice.number %>
</p>

<p>
  <strong>Order number:</strong>
  <%= @invoice.order_number %>
</p>

<p>
  <strong>Invoice date:</strong>
  <%= @invoice.invoice_date %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @invoice.salesperson %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @invoice.terms %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @invoice.due_date %>
</p>

<p>
  <strong>Line Items:</strong>
  <%= @line_items.each do |li| %>
    <%= li.description%>
  <%end%>
</p>



<%= link_to 'Edit', edit_organization_invoice_path(@organization, @invoice) %> |
<%= link_to 'Back', organization_invoices_path %>