config/routes.rb
Rails.application.routes.draw do
    root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :organizations do
    resources :invoices
    resources :customers
  end

  resources :invoices do
    resources :line_items
  end

  devise_for :users
  resources :users


end

app/models/organization.rb
class Organization < ApplicationRecord

  has_many :invoice
  has_many :customer

  validates_presence_of :name, :country, :currency, :time_zone
  validates :logo, attachment_presence: true


  has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
    @countries = Country.all
  end

  # GET /organizations/1/edit
  def edit
    @countries = Country.all
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :website, :country, :currency, :time_zone, :logo)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(organization, html: {class:'form-horizontal'}) do |f| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class:'control-label col-xs-2' %>
    <div class="col-xs-4">
      <%= f.text_field :name, class:'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :website, class:'control-label col-xs-2' %>
    <div class="col-xs-4">
      <%= f.text_field :website, class:'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :country, class:'control-label col-xs-2' %>
    <div class="col-xs-4">
      <%= f.collection_select :country, @countries, :id, :name, {}, {:class => 'required'} %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :currency, class:'control-label col-xs-2' %>
    <div class="col-xs-4">
      <%= f.text_field :currency, class:'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :time_zone, class:'control-label col-xs-2' %>
    <div class="col-xs-4">
      <%= f.text_field :time_zone, class:'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :logo, class:'control-label col-xs-2' %>
    <div class="col-xs-4">
      <%= f.file_field :logo, class:'form-control' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-success"  %>
   </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Logo</th>
      <th>Name</th>
      <th>Website</th>
      <th>Country</th>
      <th>Currency</th>
      <th>Time zone</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= link_to (image_tag organization.logo.url(:thumb)), organization%></td>
        <td><%= link_to organization.name, organization %></td>
        <td><%= organization.website %></td>
        <td><%= Country.find(organization.country).name %></td>
        <td><%= organization.currency %></td>
        <td><%= organization.time_zone %></td>
        <td>
          <%= link_to edit_organization_path(organization), class:'btn btn-primary btn-sm ' do  %>
              <span class="glyphicon glyphicon-pencil"></span>
          <%end%>
        </td>
        <td>
          <%= link_to  organization, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger btn-sm' do %>
              <span class="glyphicon glyphicon-remove"></span>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_organization_path, class:"btn btn-success" do %>
    <span class="glyphicon glyphicon-plus"></span> New Organization
<%end%>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Logo:</strong>
  <%= image_tag @organization.logo.url(:medium) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @organization.website %>
</p>

<p>
  <strong>Country:</strong>
  <%= Country.find(@organization.country).name %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @organization.currency %>
</p>

<p>
  <strong>Time zone:</strong>
  <%= @organization.time_zone %>
</p>


<row>
  <%= link_to  new_organization_invoice_path(@organization) , class:"btn btn-success" do %>
      <span class="glyphicon glyphicon-plus"></span> New Invoice
  <%end%>
  <%= link_to 'Invoices', organization_invoices_path(@organization), class:"btn btn-success"%>
  <%= link_to 'Customers',  organization_customers_path(@organization), class:"btn btn-success"  %>

</row>
<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>